stages:
- build-service
- assemble

before_script:
- df -h

after_script:
- ls -la

build-service:
  image: openjdk:13-alpine
  stage: build-service
  script:
  - ./gradlew build --build-cache --info -x test
  artifacts:
    paths:
    - service/build/libs/*.jar
    expire_in: 1 month

assemble:
  variables:
    PASSWORD: dummy
  environment:
    name: main
    url: https://api.sitesearch.cloud
  services:
  - docker:dind
  image: docker:stable
  stage: assemble
  script:
    - mkdir -p service/config/gmail-api && touch service/config/gmail-api/StoredCredential
    - cd service
    - docker build --tag docker-registry.intrafind.net/intrafind/sis-sitesearch:latest .
#  - docker push docker-registry.intrafind.net/intrafind/sis-sitesearch:latest