language: java

sudo: false # use container based builds which are faster

jdk:
- openjdk10

branches:
  only:
    - master

os:
  - linux

#before_cache:
#  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
#  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle

script:
- "./gradlew clean build -x test"

notifications:
  email:
    on_success: change
    on_failure: chnage