package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'LoadTest'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("LoadTest")) {
    expectSteps {
        script {
            scriptContent = "sh load-test.sh"
            dockerImage = "openjdk:12-jdk-alpine"
            dockerImagePlatform = ScriptBuildStep.ImagePlatform.Linux
            dockerRunParameters = "-v /root/.gradle:/root/.gradle"
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            dockerImage = "openjdk:11-jre"
        }
    }
}
