package patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.Project
import jetbrains.buildServer.configs.kotlin.v2018_2.projectFeatures.dockerRegistry
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        add {
            dockerRegistry {
                id = "PROJECT_EXT_4"
                name = "Docker Registry - IntraFind.NET"
                url = "https://docker-registry.intrafind.net"
                userName = "sitesearch"
                password = "credentialsJSON:bed82269-69df-4b8a-9435-959656fcc281"
            }
        }
    }
}
