#
# Copyright 2017 IntraFind Software AG. All rights reserved.
#

#server.error.whitelabel.enabled=false # to fix Swagger issue

logging:
  level:
    org.springframework.web: INFO
    com.intrafind: INFO

server:
  port: 8001

spring:
  groovy:
    template:
      check-template-location: false
  devtools:
    restart:
      enabled: true
  profiles:
    active: prod
  security:
    user:
      name: ${spring.security.user.password}
      password: ESqIMPNz7I2l3F6lnotc87Jh9ud97GD5bsaSKsJJafk=
  main:
    banner-mode: "off"
  output:
    ansi:
      enabled: always
  application:
    name: sitesearch