spring:
  output:
    ansi:
      enabled: detect

security:
  user:
    name: ${security.user.password}
    password: ESqIMPNz7I2l3F6lnotc87Jh9ud97GD5bsaSKsJJafk=
  oauth2:
    client:
      clientId: a4d43021fa657695d4a7
      clientSecret: ${random.uuid} # add valid token to your local configuration
    resource:
      userInfoUri: https://api.github.com/user

github:
  client:
    clientId: ${security.oauth2.client.clientId}
    clientSecret: ${security.oauth2.client.clientSecret}
    userAuthorizationUri: https://github.com/login/oauth/authorize
