---
kind: Secret
apiVersion: v1
metadata:
    name: docker-registry-credentials-intrafind-net
data:
    .dockerconfigjson: {{ .Values.app.dockerRegistrySecret }}
type: kubernetes.io/dockerconfigjson
---
kind: ConfigMap
apiVersion: v1
metadata:
    name: sis-config
data:
    logstash.conf: |
        input {
          beats {
            port => 5044
          }
        }

        filter {
            grok {
                match => {
                    "message" => [
                    "^.+ %{LOGLEVEL:log_level} .+siteId: %{UUID:siteId}"
                    ]
                }
            }

            if [message] =~ "query-fragment:" {
                grok {
                    match => {
                        "message" => "^.+query-fragment: %{WORD:query-fragment} .+autocompletes: %{NUMBER:autocompletes:int} .+autocompleteDurationInMs: %{NUMBER:autocompleteDurationInMs:int}$"
                    }
                    add_tag => [ "autocomplete" ]
                }
            }

            if [message] =~ "query:" {
                grok {
                    match => {
                        "message" => "^.+query: %{WORD:query} .+results: %{NUMBER:results:int} .+searchDurationInMs: %{NUMBER:searchDurationInMs:int}$"
                    }
                    add_tag => [ "search" ]
                }
            }

            if [message] =~ "bodySize" {
                grok {
                    match => {
                        "message" => "^.+bodySize: %{NUMBER:bodySize:int} .+titleSize: %{NUMBER:titleSize:int} .+URL: %{URI:url}$"
                    }
                    add_tag => [ "index" ]
                }
            }

            if [message] =~ " - siteUrl:" {
                grok {
                    match => {
                        "message" => "^.+siteSecret: %{UUID:siteSecret} .+siteUrl: %{URI:siteUrl} .+pageCount: %{NUMBER:pageCount:int} .+email: %{GREEDYDATA:email}$"
                    }
                    add_tag => [ "crawl" ]
                }
            }

            # if log line contains tab character followed by "at", then it is tagged as a stacktrace
            if [message] =~ "\tat" {
                grok {
                    match => ["message", "^(\tat)"]
                    add_tag => [ "stacktrace" ]
                }
            }
        }

        output {
            elasticsearch {
                hosts => [ "elasticsearch" ]
            }
        }
---
        {{/*    kubectl create secret tls test-tls --key="tls.key" --cert="tls.crt"*/}}
kind: Secret
apiVersion: v1
metadata:
    name: tls-certificate
type: kubernetes.io/tls
data:
    tls.crt: {{ .Files.Get "cert.pem" | b64enc }}
    tls.key: {{ .Files.Get "privkey.pem" | b64enc }}
---
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
    name: ingress
    annotations:
            {{/*        nginx.ingress.kubernetes.io/auth-type: basic*/}}
            {{/*        nginx.ingress.kubernetes.io/auth-secret: basic-auth*/}}
            {{/*        nginx.ingress.kubernetes.io/client-body-buffer-size: 100M*/}}
        nginx.ingress.kubernetes.io/rewrite-target: /
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/cors-allow-origin: "*"
        nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range"
        nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, OPTIONS, PUT, DELETE"
        nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
        nginx.ingress.kubernetes.io/proxy-read-timeout: 600s # required for long-lasting crawler calls
spec:
    tls:
        - secretName: tls-certificate
          hosts:
              - logging.sitesearch.cloud
              - finder.sitesearch.cloud
              - es.sitesearch.cloud
              - green.sitesearch.cloud
    rules:
        - host: logging.sitesearch.cloud
          http:
              paths:
                  - backend:
                        serviceName: sis-router
                        servicePort: 80
                    path: /
        - host: finder.sitesearch.cloud
          http:
              paths:
                  - backend:
                        serviceName: sis-router
                        servicePort: 80
                    path: /
        - host: es.sitesearch.cloud
          http:
              paths:
                  - backend:
                        serviceName: sis-router
                        servicePort: 80
                    path: /
        - host: green.sitesearch.cloud
          http:
              paths:
                  - backend:
                        serviceName: sis-router
                        servicePort: 80
                    path: /
---
kind: Service
apiVersion: v1
metadata:
    name: sis-sitesearch
spec:
    selector:
        app: sis-sitesearch
    ports:
        - port: 8001
---
kind: Service
apiVersion: v1
metadata:
    name: sis-router
spec:
    selector:
        app: sis-router
    ports:
        - port: 80
---
kind: Deployment
apiVersion: apps/v1
metadata:
    name: sis-router
    labels:
        app: sis-router
spec:
    selector:
        matchLabels:
            app: sis-router
    template:
        metadata:
            name: sis-router
            labels:
                app: sis-router
        spec:
            imagePullSecrets:
                - name: docker-registry-credentials-intrafind-net
            containers:
                - name: sis-router
                  image: docker-registry.intrafind.net/intrafind/sis-router:latest
                  env:
                      - name: BASIC_AUTH
                        value: {{ .Values.app.basicAuth }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
    name: sis-sitesearch
    labels:
        app: sis-sitesearch
spec:
    replicas: 2
    minReadySeconds: 0
    selector:
        matchLabels:
            app: sis-sitesearch
    template:
        metadata:
            name: sis-sitesearch
            labels:
                app: sis-sitesearch
        spec:
            imagePullSecrets:
                - name: docker-registry-credentials-intrafind-net
            containers:
                - name: sis-sitesearch
                  image: docker-registry.intrafind.net/intrafind/sis-sitesearch:latest
                  env:
                      - name: SIS_API_SERVICE_URL
                        value: {{ .Values.app.serviceUrl }}
                      - name: SIS_SERVICE_HOST
                        value: {{ .Values.app.serviceHost }}
                      - name: SERVICE_SECRET
                        value: {{ .Values.app.sis.serviceSecret }}
                      - name: WOO_COMMERCE_CONSUMER_KEY
                        value: {{ .Values.app.sis.wooCommerceConsumerKey }}
                      - name: WOO_COMMERCE_CONSUMER_SECRET
                        value: {{ .Values.app.sis.wooCommerceConsumerSecret }}
                      - name: INVISIBLE_RECAPTCHA_SITE_SECRET
                        value: {{ .Values.app.recaptchaSecret }}
                      - name: ADMIN_SITE_SECRET
                        value: {{ .Values.app.adminSecret }}
                      - name: DEV_SKIP_FLAG
                        value: "{{ .Values.app.devSkip }}"
                      - name: BUILD_NUMBER
                        value: "{{ .Values.app.meta.buildNumber }}"
                      - name: SCM_HASH
                        value: {{ .Values.app.meta.scmHash }}
---
kind: Secret
apiVersion: v1
metadata:
    name: hcloud-csi
    namespace: kube-system
stringData:
    token: {{ .Values.app.HETZNER_API_TOKEN }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: csi-pvc-storage
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 10Gi
    storageClassName: hcloud-volumes
    volumeName: pvc-{{ .Values.app.tenant }}
---
kind: PersistentVolume
apiVersion: v1
metadata:
    name: pvc-{{ .Values.app.tenant }}
spec:
    accessModes:
        - ReadWriteOnce
    capacity:
        storage: 10Gi
    claimRef:
        apiVersion: v1
        kind: PersistentVolumeClaim
        name: csi-pvc-storage
        namespace: {{ .Values.app.tenant }}
    csi:
        driver: csi.hetzner.cloud
        fsType: ext4
        volumeHandle: "{{ .Values.app.volumeHandle }}"
    persistentVolumeReclaimPolicy: Delete
    storageClassName: hcloud-volumes
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
    name: elasticsearch
    labels:
        app: elasticsearch
spec:
    serviceName: elasticsearch
    selector:
        matchLabels:
            app: elasticsearch
    template:
        metadata:
            name: elasticsearch
            labels:
                app: elasticsearch
        spec:
            initContainers:
                - name: set-elasticsearch-requirement
                  image: busybox
                  command: [ "sysctl", "-w", "vm.max_map_count=262144" ]
                  securityContext:
                      privileged: true
            securityContext:
                fsGroup: 1000
                runAsUser: 1000
                runAsGroup: 1000
                runAsNonRoot: true
            containers:
                - name: elasticsearch
                  image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
                  env:
                      - name: discovery.type
                        value: single-node
                      - name: bootstrap.memory_lock
                        value: "true"
                  volumeMounts:
                      - mountPath: "/usr/share/elasticsearch/data"
                        name: storage-volume
            volumes:
                - name: storage-volume
                  persistentVolumeClaim:
                      claimName: csi-pvc-storage
---
kind: Service
apiVersion: v1
metadata:
    name: elasticsearch
spec:
    selector:
        app: elasticsearch
    ports:
        - port: 9200
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
    name: logstash
    labels:
        app: logstash
spec:
    selector:
        matchLabels:
            app: logstash
    template:
        metadata:
            name: logstash
            labels:
                app: logstash
        spec:
            volumes:
                - name: config
                  configMap:
                      name: sis-config
            containers:
                - name: logstash
                  image: docker.elastic.co/logstash/logstash:7.3.2
                  volumeMounts:
                      - name: config
                        mountPath: /usr/share/logstash/pipeline/logstash.conf
                        subPath: logstash.conf
---
kind: Deployment
apiVersion: apps/v1
metadata:
    name: kibana
    labels:
        app: kibana
spec:
    selector:
        matchLabels:
            app: kibana
    template:
        metadata:
            name: kibana
            labels:
                app: kibana
        spec:
            containers:
                - name: kibana
                  image: docker.elastic.co/kibana/kibana:7.3.2
                  env:
                      - name: XPACK_TELEMETRY_ENABLED
                        value: "false"
                      - name: XPACK_SECURITY_ENABLED
                        value: "true"
                      - name: ELASTICSEARCH_HOSTS
                        value: http://elasticsearch:9200
---
kind: Service
apiVersion: v1
metadata:
    name: kibana
spec:
    selector:
        app: kibana
    ports:
        - port: 5601
---
kind: Service
apiVersion: v1
metadata:
    name: logstash
spec:
    selector:
        app: logstash
    ports:
        - port: 5044
---
kind: Secret
apiVersion: v1
data:
    auth: {{ .Values.app.basicAuthBase64 }}
metadata:
    name: basic-auth
type: Opaque
---