# Default values for page-finder.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#replicaCount: 1

#image:
#  repository: nginx
#  tag: stable
#  pullPolicy: IfNotPresent

#imagePullSecrets: []
#nameOverride: ""
#fullnameOverride: ""

#service:
#  type: ClusterIP
#  port: 80

#ingress:
#  enabled: false
#  annotations: {}
#  hosts:
#    - host: chart-example.local
#      paths: []
#
#  tls: []
#
#resources: {}
#nodeSelector: {}
#tolerations: []
#affinity: {}

app:
  tenant: none
  password: invalid-default
  dockerRegistrySecret: invalid-default
  HETZNER_API_TOKEN: invalid-default
  volumeHandle: invalid-default
  EXTERNAL_IP: 0.0.0.0