version: "2.0"
services:
  ops-kibana:
    image: docker.elastic.co/kibana/kibana:6.4.3
    container_name: ops-kibana
    depends_on:
      - elk-elasticsearch
      - ops-elasticsearch-yang
      - ops-elasticsearch-ying
      - ops-logstash
    environment:
      - xpack.security.enabled=false
      - xpack.monitoring.report_stats=false
      - xpack.monitoring.collection.enabled=true
      - ELASTICSEARCH_URL=http://elk-elasticsearch:9200
    networks:
      - sitesearch

  elk-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    container_name: elk-elasticsearch
    environment:
      #      - "discovery.type=single-node"
      - xpack.security.enabled=false
      - cluster.name=sitesearch-ops-cluster
      - bootstrap.memory_lock=true
      - node.name=elk-elasticsearch
      - discovery.zen.ping.unicast.hosts=elk-elasticsearch,ops-elasticsearch-ying,ops-elasticsearch-yang
    #      - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /srv/elk-elasticsearch/data:/usr/share/elasticsearch/data:rw
    networks:
      - sitesearch

  ops-elasticsearch-ying:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    container_name: ops-elasticsearch-ying
    environment:
      - xpack.security.enabled=false
      - cluster.name=sitesearch-ops-cluster
      - bootstrap.memory_lock=true
      - node.name=ops-elasticsearch-ying
      - discovery.zen.ping.unicast.hosts=elk-elasticsearch,ops-elasticsearch-ying,ops-elasticsearch-yang
    #      - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /srv/ops-elasticsearch-ying/data:/usr/share/elasticsearch/data:rw
    networks:
      - sitesearch

  ops-elasticsearch-yang:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    container_name: ops-elasticsearch-yang
    environment:
      - xpack.security.enabled=false
      - cluster.name=sitesearch-ops-cluster
      - bootstrap.memory_lock=true
      - node.name=ops-elasticsearch-yang
      - discovery.zen.ping.unicast.hosts=elk-elasticsearch,ops-elasticsearch-ying,ops-elasticsearch-yang
    #      - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /srv/ops-elasticsearch-yang/data:/usr/share/elasticsearch/data:rw
    networks:
      - sitesearch

  ops-logstash:
    image: docker.elastic.co/logstash/logstash:6.4.3
    container_name: ops-logstash
    volumes:
      - /srv/ops-logstash/_data:/usr/share/logstash:rw
    ports:
      - 12201:12201/udp
    networks:
      - sitesearch

networks:
  sitesearch:
    external:
      name: sitesearch