version: "3"
services:
  ops-kibana:
    image: docker.elastic.co/kibana/kibana:6.4.3
    container_name: ops-kibana
    depends_on:
      - ops-elasticsearch
      - ops-elasticsearch-yang
      - ops-logstash
    environment:
      - xpack.security.enabled=false
      - xpack.monitoring.report_stats=false
      - xpack.monitoring.collection.enabled=true
      - ELASTICSEARCH_URL=http://ops-elasticsearch:9200
    networks:
      - main

  ops-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    container_name: ops-elasticsearch
    environment:
      #      - "discovery.type=single-node"
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - node.name=elk-elasticsearch
      - discovery.zen.ping.unicast.hosts=ops-elasticsearch,ops-elasticsearch-yang
      - "ES_JAVA_OPTS=-Xms3g -Xmx3g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /mnt/elk/ops-elasticsearch/data:/usr/share/elasticsearch/data:rw
    networks:
      - main

  ops-elasticsearch-ying:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    container_name: ops-elasticsearch-ying
    environment:
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - node.name=ops-elasticsearch-ying
      - discovery.zen.ping.unicast.hosts=ops-elasticsearch,ops-elasticsearch-yang,ops-elasticsearch-ying
      - "ES_JAVA_OPTS=-Xms3g -Xmx3g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /mnt/elk/ops-elasticsearch-ying/data:/usr/share/elasticsearch/data:rw
    networks:
      - main

  ops-elasticsearch-yang:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    container_name: ops-elasticsearch-yang
    environment:
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - node.name=ops-elasticsearch-yang
      - discovery.zen.ping.unicast.hosts=ops-elasticsearch,ops-elasticsearch-yang
      - "ES_JAVA_OPTS=-Xms3g -Xmx3g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /mnt/elk/ops-elasticsearch-yang/data:/usr/share/elasticsearch/data:rw
    networks:
      - main

  ops-logstash:
    image: docker.elastic.co/logstash/logstash:6.4.3
    container_name: ops-logstash
    volumes:
      - /mnt/elk/ops-logstash/_data:/usr/share/logstash:rw
    ports:
      - 12201:12201/udp
    networks:
      - main

networks:
  main:
    external:
      name: main