version: '3.5'

services:

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${SERVICE_SECRET}

  wordpress:
    image: wordpress:4.9.7-apache
    depends_on:
    - mysql
    restart: unless-stopped
    ports:
    - 7080:80
    environment:
    - WORDPRESS_DB_PASSWORD=${SERVICE_SECRET}
    - WORDPRESS_USERNAME=sitesearch
    - WORDPRESS_PASSWORD=sitesearch
    - WORDPRESS_EMAIL=alexander.orlov@intrafind.de
    - WORDPRESS_FIRST_NAME=Alexander
    - WORDPRESS_LAST_NAME=Orlov
    - WORDPRESS_BLOG_NAME=SiteSearch

networks:
  default:
    external:
      name: sitesearch