version: '3.5'

services:

  mysql:
    image: mysql:5.7
    #    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${SERVICE_SECRET}
  #    networks:
  #    - sitesearch

  #  mariadb:
  #    image: mariadb:5
  #    restart: unless-stopped
  #    environment:
  ##      - MYSQL_USER=bn_wordpress
  ##      - MYSQL_DATABASE=bitnami_wordpress
  ##      - ALLOW_EMPTY_PASSWORD=yes
  #      - MYSQL_ROOT_PASSWORD=${SERVICE_SECRET}
  ##      MYSQL_ROOT_PASSWORD: ${SERVICE_SECRET}
  #    networks:
  #    - sitesearch

  wordpress:
    #    image: wordpress:4.9.7-fpm-alpine
    image: wordpress:4.9.7-apache
    #    depends_on:
    #    - mariadb
    #    - mysql
    restart: unless-stopped
    ports:
    - 7080:80
    environment:
    #    - MYSQL_HOST=mariadb
    #    - MYSQL_PORT_NUMBER=3306
    #    - WORDPRESS_DATABASE_USER=bn_wordpress
    #    - WORDPRESS_DATABASE_NAME=bitnami_wordpress
    #    - ALLOW_EMPTY_PASSWORD=yes
    - WORDPRESS_DB_PASSWORD=${SERVICE_SECRET}
    - WORDPRESS_USERNAME=sitesearch
    - WORDPRESS_PASSWORD=sitesearch
    - WORDPRESS_EMAIL=alexander.orlov@intrafind.de
    - WORDPRESS_FIRST_NAME=Alexander
    - WORDPRESS_LAST_NAME=Orlov
    - WORDPRESS_BLOG_NAME=SiteSearch
#    networks:
#      - sitesearch

networks:
  default:
    external:
      name: sitesearch
#networks:
#  sitesearch:
#    external:
#      name: sitesearch